nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  host: ""

sqlxMigrator:
  # repository that hosts the migration files
  repo: "https://github.com/Tortoaster/toast.git"
  # revision (branch/tag/hash) that contains the most complete list of migrations - this usually only needs to be changed if you want to test new migrations on a different branch
  rev: "HEAD"
  # directory within the repository that contains the migrations
  migrationsDir: "migrations"
  # version of the most recent migration that is compatible with this version of the application - note that this is always a number like 20250207222531, but be sure to put it between quotes to prevent YAML from converting it to scientific notation
  targetVersion: "20240513174947"
  image:
    registry: "ghcr.io/tortoaster"
    name: "sqlx-migrator"
    tag: "v1.0.0"

deploy:
  replicas: 1
  containerPort: 8000
  logLevel: "toast=info,warn"
  image:
    registry: "ghcr.io/tortoaster"
    name: "toast"
    tag: "v1.3.0"

db:
  user:
    # name of the unprivileged database user
    name: ""
    passwordSecret:
      # name of the secret resource that contains the unprivileged user's database password
      name: ""
      # key of the secret that corresponds to the unprivileged user's database password
      key: ""
  admin:
    # name of the admin database user
    name: "postgres"
    passwordSecret:
      # name of the secret resource that contains the admin user's database password
      name: ""
      # key within the secret that corresponds to the admin user's database password
      key: ""
  # host that serves the database
  host: ""
  # port the database listens to
  port: 5432
  # database name
  database: ""

s3:
  region: ""
  endpointUrl: ""
  accessKeyId: ""
  secret:
    # name of te secret resource that contains the S3 secret access key
    name: ""
    # key of the secret that corresponds to the S3 secret access key
    key: ""
  bucketName: "toast"

oidc:
  clientId: ""
  issuerUrl: ""
  redirectUrl: ""
  secret:
    # name of te secret resource that contains the OIDC client secret
    name: ""
    # key of the secret that corresponds to the OIDC client secret
    key: ""
