nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  host: ""

sqlxMigrator:
  # repository that hosts the migration files
  repo: "https://github.com/Tortoaster/toast.git"
  # revision (branch/tag/hash) that contains the most complete list of migrations - this usually only needs to be changed if you want to test new migrations on a different branch
  rev: "HEAD"
  # directory within the repository that contains the migrations
  migrationsDir: "migrations"
  # version of the most recent migration that is compatible with this version of the application - note that this is always a number like 20250207222531, but be sure to put it between quotes to prevent YAML from converting it to scientific notation
  targetVersion: "20240513174947"
  image:
    registry: "ghcr.io/tortoaster"
    name: "sqlx-migrator"
    tag: "v1.0.0"

deploy:
  replicas: 1
  containerPort: 8000
  logLevel: "toast=info,warn"
  image:
    registry: "ghcr.io/tortoaster"
    name: "toast"
    tag: "v1.4.0"

db:
  # name of the database user
  username: ""
  # host that serves the database
  host: ""
  # port the database listens to
  port: 5432
  # database name
  database: ""
