{{ if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "beegone.fullname" . }}
  labels:
    {{- include "beegone.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host | required "ingress.host required" }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "beegone.fullname" $ }}
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.ingress.host | required "ingress.host required" }}
      secretName: {{ include "beegone.fullname" $ }}
{{- end }}
