apiVersion: v1
kind: Service
metadata:
  name: {{ include "beegone.fullname" . }}
  labels:
    {{- include "beegone.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 8000
  selector:
    {{- include "beegone.selectorLabels" . | nindent 4 }}
