apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "toast.fullname" . }}
  labels:
    {{- include "toast.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      {{- include "toast.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "toast.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: "sqlx-migrator"
          {{- with .Values.sqlxMigrator.image}}
          image: "{{ .registry }}/{{ .name }}:{{ .tag }}"
          {{- end }}
          env:
            {{- with .Values.sqlxMigrator }}
            - name: "REPO"
              value: {{ .repo }}
            - name: "REV"
              value: {{ .rev }}
            - name: "MIGRATIONS_DIR"
              value: {{ .migrationsDir }}
            - name: "TARGET_VERSION"
              value: {{ .targetVersion }}
            {{- end }}
            {{- with .Values.db }}
            - name: "DATABASE_URL"
              value: {{ .url | required "db.url required" }}
            {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.deploy.image}}
          image: "{{ .registry }}/{{ .name }}:{{ .tag }}"
          {{- end }}
          ports:
            - containerPort: {{ .Values.deploy.containerPort }}
          env:
            - name: "HOST"
              value: "0.0.0.0"
            - name: "PORT"
              value: {{ .Values.deploy.containerPort | quote }}
            - name: "RUST_LOG"
              value: {{ .Values.deploy.logLevel }}
            {{- with .Values.db }}
            - name: "DATABASE__URL"
              value: {{ .url | required "db.url required" }}
            {{- end }}
